name: Release

on:
  push:
    branches:
      - main  

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1  

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: npx semantic-release
